[2025-05-21 13:50:11,088 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 13:50:11,090 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 13:50:11,192 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 13:50:11,193 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 13:53:03,810 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 13:53:03,811 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 13:53:03,965 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 13:53:03,967 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 13:53:04,032 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 13:53:04,033 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 13:53:04,065 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 13:53:04,066 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 13:53:04,077 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 13:53:04,078 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 13:53:04,113 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 13:53:04,113 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 13:55:27,619 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 13:55:27,621 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 13:55:27,689 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 13:55:27,690 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 13:55:27,744 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 13:55:27,745 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 13:55:27,801 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 13:55:27,802 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 13:55:27,807 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 13:55:27,808 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 13:55:48,195 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 13:56:29,624 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 13:56:29,625 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 13:56:29,647 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 13:56:29,648 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 13:56:29,666 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 13:56:29,667 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 13:56:29,688 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 13:56:29,689 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 13:56:29,705 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 13:56:29,706 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 13:56:29,716 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 13:56:29,716 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 13:56:29,717 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 13:56:29,717 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 13:59:13,936 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 13:59:13,937 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 13:59:14,019 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 13:59:14,020 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 13:59:14,060 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 13:59:14,061 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 13:59:14,141 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 13:59:14,142 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 14:02:05,285 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 14:02:05,286 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 14:02:05,355 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:02:05,356 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:02:05,566 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 14:02:05,567 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 14:04:51,125 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:04:51,126 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:04:51,292 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 14:04:51,293 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 14:04:51,333 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 14:04:51,334 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 14:05:12,436 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 14:06:17,364 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 14:06:17,365 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 14:06:17,451 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 14:06:17,452 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 14:06:17,527 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:06:17,528 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:06:17,606 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 14:06:17,607 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 14:06:17,671 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 14:06:17,672 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 14:06:17,710 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 14:06:17,711 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 14:09:29,948 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 14:09:29,949 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 14:09:30,034 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:09:30,034 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:09:30,115 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 14:09:30,116 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 14:09:30,157 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 14:09:30,158 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 14:09:30,246 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 14:09:30,247 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 14:12:40,091 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 14:12:40,093 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 14:12:40,218 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:12:40,219 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:12:40,309 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 14:12:40,310 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 14:12:40,364 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 14:12:40,364 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 14:13:00,804 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 14:14:37,474 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:14:37,475 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:17:37,181 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 14:17:37,182 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 14:17:37,305 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:17:37,306 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:17:37,393 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 14:17:37,394 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 14:17:37,404 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 14:17:37,405 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 14:17:37,432 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 14:17:37,433 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 14:17:57,942 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 14:19:28,731 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 14:19:28,732 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 14:19:28,792 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 14:19:28,792 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 14:19:28,841 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:19:28,841 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:19:28,890 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 14:19:28,890 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 14:19:28,933 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 14:19:28,933 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 14:19:28,959 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 14:19:28,960 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 14:22:27,118 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 14:22:27,119 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 14:22:27,182 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 14:22:27,182 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 14:22:27,234 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:22:27,235 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:22:27,374 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 14:22:27,375 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 14:22:27,376 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 14:22:27,376 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 14:22:47,901 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 14:24:03,655 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 14:24:03,656 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 14:24:03,758 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 14:24:03,759 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 14:24:03,838 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:24:03,839 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:24:04,118 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 14:24:04,119 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 14:24:04,120 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 14:24:04,121 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 14:24:24,708 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 14:25:28,855 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 14:25:28,856 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 14:25:28,916 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 14:25:28,917 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 14:25:28,965 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:25:28,966 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:25:29,046 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 14:25:29,047 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 14:25:29,055 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 14:25:29,056 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 14:25:29,081 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 14:25:29,081 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 14:25:29,082 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 14:25:29,083 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 14:28:25,549 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 14:28:25,551 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 14:28:25,613 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 14:28:25,614 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 14:28:25,668 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:28:25,669 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:28:25,724 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 14:28:25,725 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 14:28:25,753 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 14:28:25,754 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 14:28:25,764 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 14:28:25,765 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 14:28:25,793 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 14:28:25,794 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 14:28:46,422 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 14:30:35,890 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 14:30:35,892 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 14:30:36,016 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:30:36,017 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:30:36,108 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 14:30:36,109 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 14:30:36,118 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 14:30:36,119 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 14:30:36,145 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 14:30:36,146 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 14:30:36,148 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 14:30:36,149 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 14:33:23,001 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 14:33:23,002 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 14:33:23,125 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:33:23,126 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:33:23,179 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 14:33:23,180 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 14:33:23,259 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 14:33:23,260 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 14:33:23,261 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 14:33:23,262 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 14:33:44,980 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 14:35:16,547 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:35:16,548 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:35:16,606 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 14:35:16,607 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 14:35:16,652 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 14:35:16,653 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 14:35:16,680 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 14:35:16,680 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 14:38:31,134 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 14:38:31,136 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 14:38:31,475 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:38:31,476 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:38:31,637 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 14:38:31,637 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 14:38:31,753 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 14:38:31,754 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 14:38:31,816 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 14:38:31,817 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 14:41:24,958 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 14:41:24,959 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 14:41:25,222 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:41:25,223 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:41:25,310 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 14:41:25,311 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 14:41:25,354 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 14:41:25,355 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 14:44:30,142 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 14:44:30,143 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 14:44:30,349 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:44:30,350 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:44:30,437 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 14:44:30,437 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 14:44:30,481 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 14:44:30,482 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 14:44:30,498 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 14:44:30,499 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 14:44:30,545 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 14:44:30,546 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 14:47:47,421 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 14:47:47,422 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 14:47:47,562 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:47:47,563 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:47:47,666 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 14:47:47,667 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 14:47:47,679 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 14:47:47,680 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 14:47:47,710 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 14:47:47,710 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 14:51:21,939 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 14:51:21,940 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 14:51:22,031 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:51:22,032 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:51:22,300 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 14:51:22,300 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 14:54:58,589 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 14:54:58,591 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 14:54:58,696 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 14:54:58,697 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 14:54:58,790 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:54:58,791 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:54:59,017 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 14:54:59,018 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 14:54:59,054 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 14:54:59,055 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 14:54:59,097 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 14:54:59,098 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 14:55:20,173 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 14:57:06,956 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 14:57:06,957 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 14:57:07,093 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 14:57:07,093 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 14:57:07,154 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 14:57:07,155 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 14:57:07,238 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 14:57:07,239 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 14:57:07,240 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 14:57:07,241 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 15:00:03,320 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 15:00:03,321 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 15:00:03,455 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 15:00:03,456 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 15:00:03,521 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 15:00:03,522 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 15:00:03,552 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 15:00:03,553 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 15:00:03,563 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 15:00:03,564 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 15:00:03,593 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 15:00:03,594 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 15:00:25,644 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 15:01:45,673 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 15:01:45,674 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 15:01:45,733 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 15:01:45,734 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 15:01:45,784 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 15:01:45,785 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 15:01:45,839 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 15:01:45,839 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 15:01:45,883 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 15:01:45,884 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 15:01:45,911 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 15:01:45,911 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 15:04:31,211 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 15:04:31,212 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 15:04:31,278 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 15:04:31,279 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 15:04:31,335 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 15:04:31,337 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 15:04:31,390 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 15:04:31,391 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 15:13:07,666 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 15:13:07,668 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 15:13:07,814 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 15:13:07,815 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 15:13:07,872 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 15:13:07,872 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 15:13:07,919 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 15:13:07,919 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 15:16:28,357 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 15:16:28,359 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 15:16:28,427 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 15:16:28,427 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 15:16:28,488 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 15:16:28,489 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 15:16:28,543 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 15:16:28,544 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 15:16:28,591 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 15:16:28,592 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 15:19:26,923 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 15:19:26,924 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 15:19:26,981 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 15:19:26,982 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 15:19:27,033 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 15:19:27,034 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 15:19:27,083 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 15:19:27,084 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 15:19:27,129 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 15:19:27,129 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 15:19:27,153 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 15:19:27,153 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 15:22:30,315 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 15:22:30,316 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 15:22:30,371 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 15:22:30,372 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 15:22:30,428 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 15:22:30,429 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 15:22:30,482 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 15:22:30,483 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 15:22:30,512 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 15:22:30,513 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 15:25:46,576 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 15:25:46,577 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 15:25:46,699 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 15:25:46,700 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 15:28:49,000 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 15:28:49,002 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 15:28:49,139 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 15:28:49,140 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 15:28:49,201 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 15:28:49,202 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 15:28:49,252 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 15:28:49,253 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 15:32:20,337 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 15:32:20,339 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 15:32:20,403 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 15:32:20,404 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 15:32:20,461 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 15:32:20,462 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 15:32:20,521 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 15:32:20,522 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 15:32:20,571 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 15:32:20,572 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 15:35:34,301 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 15:35:34,303 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 15:35:34,435 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 15:35:34,436 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 15:35:34,550 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 15:35:34,551 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 15:38:54,637 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 15:38:54,638 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 15:38:54,705 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 15:38:54,705 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 15:38:54,762 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 15:38:54,762 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 15:38:54,867 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 15:38:54,867 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 15:38:54,895 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 15:38:54,896 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 15:42:09,340 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 15:42:09,341 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 15:42:09,401 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 15:42:09,402 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 15:42:09,464 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 15:42:09,465 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 15:42:09,497 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 15:42:09,498 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 15:42:09,509 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 15:42:09,510 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 15:42:09,539 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 15:42:09,540 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 15:45:41,678 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 15:45:41,679 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 15:45:41,775 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 15:45:41,776 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 15:45:41,858 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 15:45:41,859 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 15:45:42,014 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 15:45:42,014 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 15:45:42,053 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 15:45:42,054 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 15:49:00,757 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 15:49:00,759 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 15:49:01,021 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 15:49:01,022 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 15:49:01,298 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 15:49:01,299 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 15:49:01,401 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 15:49:01,402 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 15:49:01,413 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 15:49:01,414 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 15:49:01,508 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 15:49:01,509 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 15:52:32,593 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 15:52:32,594 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 15:52:32,704 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 15:52:32,705 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 15:52:32,803 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 15:52:32,804 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 15:52:32,892 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 15:52:32,893 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 15:52:32,970 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 15:52:32,971 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 15:52:33,088 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 15:52:33,089 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 15:52:33,091 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 15:52:33,091 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 15:55:55,843 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 15:55:55,845 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 15:55:55,927 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 15:55:55,928 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 15:55:55,991 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 15:55:55,992 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 15:55:56,101 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 15:55:56,103 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 15:55:56,236 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 15:55:56,236 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 15:59:21,436 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 15:59:21,469 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 15:59:21,747 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 15:59:21,748 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 15:59:22,003 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 15:59:22,004 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 15:59:22,266 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 15:59:22,266 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 15:59:22,280 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 15:59:22,280 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 15:59:22,324 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 15:59:22,325 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 15:59:43,223 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 16:01:44,198 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 16:01:44,199 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 16:01:44,392 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:01:44,392 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:01:44,472 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 16:01:44,472 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 16:01:44,610 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 16:01:44,611 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 16:01:44,612 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 16:01:44,612 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 16:05:11,291 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 16:05:11,293 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 16:05:11,459 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:05:11,459 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:05:11,536 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 16:05:11,537 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 16:05:11,582 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 16:05:11,583 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 16:05:11,593 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 16:05:11,594 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 16:05:11,628 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 16:05:11,629 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 16:05:34,729 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 16:07:45,764 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 16:07:45,765 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 16:07:45,857 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 16:07:45,858 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 16:07:45,975 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:07:45,977 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:07:46,380 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 16:07:46,381 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 16:07:46,588 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 16:07:46,588 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 16:11:16,657 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 16:11:16,658 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 16:11:16,715 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:11:16,716 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:14:32,981 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 16:14:32,982 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 16:14:33,035 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:14:33,035 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:14:33,126 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 16:14:33,127 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 16:14:33,138 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 16:14:33,139 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 16:14:33,169 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 16:14:33,170 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 16:18:13,483 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 16:18:13,484 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 16:18:13,547 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 16:18:13,547 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 16:18:13,600 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:18:13,600 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:18:13,700 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 16:18:13,701 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 16:21:41,628 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 16:21:41,630 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 16:21:41,754 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:21:41,755 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:21:41,862 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 16:21:41,863 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 16:21:41,890 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 16:21:41,891 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 16:25:21,694 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 16:25:21,696 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 16:25:21,838 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:25:21,839 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:25:21,958 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 16:25:21,959 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 16:25:21,990 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 16:25:21,991 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 16:28:56,236 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 16:28:56,238 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 16:28:56,408 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 16:28:56,409 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 16:28:56,533 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:28:56,533 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:28:56,851 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 16:28:56,852 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 16:28:56,917 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 16:28:56,918 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 16:32:49,239 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 16:32:49,241 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 16:32:49,453 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:32:49,454 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:32:49,601 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 16:32:49,602 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 16:32:49,616 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 16:32:49,617 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 16:32:49,670 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 16:32:49,670 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 16:33:13,422 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 16:35:33,215 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:35:33,216 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:35:33,388 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 16:35:33,388 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 16:35:33,439 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 16:35:33,440 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 16:35:33,490 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 16:35:33,491 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 16:35:54,673 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 16:37:57,635 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 16:37:57,637 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 16:37:57,700 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 16:37:57,701 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 16:37:57,755 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:37:57,756 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:37:57,808 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 16:37:57,809 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 16:37:57,892 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 16:37:57,893 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 16:37:57,894 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 16:37:57,894 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 16:41:27,889 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 16:41:27,891 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 16:41:27,966 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:41:27,967 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:41:28,127 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 16:41:28,128 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 16:41:28,139 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 16:41:28,139 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 16:41:28,200 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 16:41:28,201 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 16:44:20,239 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 16:44:20,240 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 16:44:20,305 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 16:44:20,305 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 16:44:20,362 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:44:20,362 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:44:20,471 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 16:44:20,472 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 16:44:20,504 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 16:44:20,505 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 16:44:41,102 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 16:46:54,970 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:46:54,971 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:46:55,355 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 16:46:55,356 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 16:46:55,406 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 16:46:55,407 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 16:46:55,518 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 16:46:55,519 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 16:49:56,855 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 16:49:56,857 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 16:49:56,909 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:49:56,910 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:49:56,994 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 16:49:56,995 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 16:49:57,005 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 16:49:57,006 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 16:49:57,037 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 16:49:57,038 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 16:50:17,621 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 16:52:04,734 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 16:52:04,735 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 16:52:04,800 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 16:52:04,801 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 16:52:04,852 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:52:04,853 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:52:04,946 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 16:52:04,947 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 16:52:04,957 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 16:52:04,957 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 16:52:04,983 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 16:52:04,984 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 16:52:28,446 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 16:53:58,995 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 16:53:58,997 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 16:53:59,059 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 16:53:59,060 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 16:53:59,113 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:53:59,113 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:53:59,200 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 16:53:59,201 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 16:53:59,211 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 16:53:59,212 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 16:53:59,239 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 16:53:59,240 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 16:57:16,395 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 16:57:16,396 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 16:57:16,518 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 16:57:16,519 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 16:57:16,613 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 16:57:16,614 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 16:57:16,625 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 16:57:16,626 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 16:57:16,655 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 16:57:16,656 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 17:00:46,001 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 17:00:46,002 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 17:00:46,060 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 17:00:46,060 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 17:00:46,115 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 17:00:46,116 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 17:00:46,144 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 17:00:46,145 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 17:00:46,155 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 17:00:46,156 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 17:00:46,193 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 17:00:46,194 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 17:04:32,698 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 17:04:32,699 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 17:04:32,809 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 17:04:32,810 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 17:04:32,902 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 17:04:32,903 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 17:04:33,083 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 17:04:33,083 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 17:04:33,129 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 17:04:33,130 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 17:07:30,936 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 17:07:30,937 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 17:07:31,137 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 17:07:31,138 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 17:07:31,262 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 17:07:31,263 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 17:07:31,409 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 17:07:31,410 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 17:10:25,253 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 17:10:25,255 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 17:10:25,307 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 17:10:25,308 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 17:10:25,396 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 17:10:25,396 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 17:10:25,407 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 17:10:25,408 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 17:10:25,436 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 17:10:25,437 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 17:10:25,438 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 17:10:25,438 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 17:14:18,295 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 17:14:18,296 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 17:14:18,365 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 17:14:18,366 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 17:14:18,422 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 17:14:18,423 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 17:14:18,551 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 17:14:18,551 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 17:14:18,583 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 17:14:18,583 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 17:17:17,154 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 17:17:17,155 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 17:17:17,225 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 17:17:17,226 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 17:17:17,285 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 17:17:17,286 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 17:17:17,383 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 17:17:17,384 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 17:17:17,395 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 17:17:17,396 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 17:17:17,425 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 17:17:17,426 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 17:17:40,875 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 17:19:35,175 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 17:19:35,176 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 17:19:35,234 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 17:19:35,235 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 17:19:35,492 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 17:19:35,493 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 17:19:35,557 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 17:19:35,558 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 17:22:49,458 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 17:22:49,459 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 17:26:25,375 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 17:26:25,377 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 17:26:25,428 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 17:26:25,429 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 17:26:25,605 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 17:26:25,606 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 17:29:59,398 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 17:29:59,399 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 17:29:59,463 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 17:29:59,464 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 17:29:59,520 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 17:29:59,521 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 17:29:59,577 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 17:29:59,577 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 17:29:59,661 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 17:29:59,662 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 17:29:59,663 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 17:29:59,663 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 17:30:20,193 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 17:32:26,906 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 17:32:26,907 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 17:32:26,961 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 17:32:26,962 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 17:32:27,048 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 17:32:27,049 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 17:36:03,151 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 17:36:03,154 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 17:36:03,306 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 17:36:03,308 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 17:36:03,390 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 17:36:03,391 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 17:39:47,925 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 17:39:47,926 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 17:39:47,979 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 17:39:47,980 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 17:39:48,035 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 17:39:48,035 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 17:39:48,115 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 17:39:48,115 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 17:43:25,849 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 17:43:25,850 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 17:43:25,918 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 17:43:25,919 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 17:43:25,974 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 17:43:25,975 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 17:43:26,033 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 17:43:26,034 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 17:43:26,064 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 17:43:26,064 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 17:43:26,075 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 17:43:26,076 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 17:46:53,733 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 17:46:53,735 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 17:46:53,792 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 17:46:53,793 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 17:46:53,822 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 17:46:53,823 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 17:50:32,668 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 17:50:32,669 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 17:50:32,730 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 17:50:32,731 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 17:50:32,784 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 17:50:32,784 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 17:50:32,862 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 17:50:32,863 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 17:50:32,889 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 17:50:32,890 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 17:50:32,900 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 17:50:32,901 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 17:50:32,928 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 17:50:32,929 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 17:54:06,806 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 17:54:06,807 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 17:54:06,874 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 17:54:06,875 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 17:54:06,929 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 17:54:06,930 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 17:54:07,019 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 17:54:07,020 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 17:54:07,030 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 17:54:07,030 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 17:57:41,177 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 17:57:41,178 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 17:57:41,274 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 17:57:41,275 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 17:57:41,285 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 17:57:41,285 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 18:01:18,614 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 18:01:18,615 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 18:01:18,676 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:01:18,677 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:01:18,733 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 18:01:18,733 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 18:01:18,761 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 18:01:18,761 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 18:04:55,425 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 18:04:55,426 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 18:04:55,484 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:04:55,485 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:04:55,578 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 18:04:55,579 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 18:04:55,630 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 18:04:55,630 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 18:04:55,631 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 18:04:55,632 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 18:05:16,211 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 18:07:23,057 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 18:07:23,058 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 18:07:23,108 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:07:23,108 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:07:23,158 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 18:07:23,158 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 18:10:37,569 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:10:37,570 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:10:37,676 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 18:10:37,677 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 18:10:37,712 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 18:10:37,713 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 18:11:02,068 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 18:12:58,510 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 18:12:58,512 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 18:12:58,569 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:12:58,569 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:12:58,660 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 18:12:58,661 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 18:12:58,706 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 18:12:58,707 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 18:16:44,787 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 18:16:44,788 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 18:16:44,839 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:16:44,840 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:16:44,891 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 18:16:44,892 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 18:16:44,917 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 18:16:44,918 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 18:16:44,927 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 18:16:44,927 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 18:16:44,952 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 18:16:44,953 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 18:20:20,120 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:20:20,122 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:20:20,175 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 18:20:20,176 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 18:20:20,253 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 18:20:20,254 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 18:23:54,543 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 18:23:54,545 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 18:23:54,607 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 18:23:54,608 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 18:23:54,659 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:23:54,660 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:23:54,761 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 18:23:54,761 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 18:27:32,317 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 18:27:32,318 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 18:27:32,378 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 18:27:32,379 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 18:27:32,426 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:27:32,427 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:27:32,518 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 18:27:32,519 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 18:27:32,550 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 18:27:32,551 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 18:27:53,063 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 18:29:44,501 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 18:29:44,502 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 18:29:44,872 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:29:44,873 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:29:45,135 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 18:29:45,137 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 18:29:45,147 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 18:29:45,148 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 18:29:45,242 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 18:29:45,243 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 18:32:58,928 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:32:58,929 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:32:59,025 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 18:32:59,026 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 18:32:59,075 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 18:32:59,076 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 18:36:10,512 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:36:10,514 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:36:10,808 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 18:36:10,809 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 18:36:10,838 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 18:36:10,839 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 18:36:33,042 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 18:38:41,826 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 18:38:41,828 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 18:38:41,951 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:38:41,952 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:38:42,004 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 18:38:42,005 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 18:38:42,031 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 18:38:42,032 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 18:38:42,083 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 18:38:42,084 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 18:39:05,088 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 18:40:49,339 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:40:49,340 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:40:49,388 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 18:40:49,389 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 18:40:49,414 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 18:40:49,414 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 18:40:49,424 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 18:40:49,424 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 18:40:49,449 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 18:40:49,449 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 18:43:56,386 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:43:56,387 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:43:56,439 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 18:43:56,439 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 18:43:56,466 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 18:43:56,466 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 18:43:56,476 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 18:43:56,476 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 18:43:56,511 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 18:43:56,511 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 18:47:15,988 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 18:47:15,990 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 18:47:16,126 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:47:16,127 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:47:16,286 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 18:47:16,287 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 18:47:16,402 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 18:47:16,403 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 18:47:16,466 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 18:47:16,468 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 18:50:39,540 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 18:50:39,541 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 18:50:39,595 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:50:39,595 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:50:39,649 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 18:50:39,650 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 18:50:39,679 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 18:50:39,680 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 18:50:39,690 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 18:50:39,690 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 18:54:01,753 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 18:54:01,755 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 18:54:01,818 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 18:54:01,819 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 18:54:01,872 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:54:01,873 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:54:02,090 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 18:54:02,090 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 18:57:08,389 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 18:57:08,390 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 18:57:08,445 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 18:57:08,445 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 18:57:08,532 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 18:57:08,533 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 18:57:08,627 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 18:57:08,627 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 18:57:08,639 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 18:57:08,639 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 18:57:08,704 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 18:57:08,705 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 19:00:43,318 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 19:00:43,319 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 19:00:43,372 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 19:00:43,372 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 19:00:43,424 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 19:00:43,425 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 19:00:43,469 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 19:00:43,470 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 19:04:41,817 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 19:04:41,818 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 19:04:41,959 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 19:04:41,959 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 19:04:41,960 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 19:04:41,961 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 19:08:23,158 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 19:08:23,160 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 19:08:23,215 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 19:08:23,216 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 19:08:23,272 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 19:08:23,273 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 19:08:23,302 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 19:08:23,303 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 19:08:23,351 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 19:08:23,351 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 19:12:17,584 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 19:12:17,586 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 19:12:17,648 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 19:12:17,649 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 19:12:17,704 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 19:12:17,705 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 19:12:17,762 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 19:12:17,763 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 19:12:17,810 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 19:12:17,811 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 19:12:17,839 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 19:12:17,840 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 19:16:37,969 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 19:16:37,970 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 19:16:38,097 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 19:16:38,098 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 19:16:38,151 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 19:16:38,152 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 19:16:38,180 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 19:16:38,181 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 19:16:38,191 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 19:16:38,192 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 19:16:38,230 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 19:16:38,230 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 19:16:58,792 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 19:19:00,944 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-21 19:19:00,946 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-21 19:19:00,998 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 19:19:00,998 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 19:19:01,048 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 19:19:01,049 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 19:19:01,088 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 19:19:01,088 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 19:19:01,112 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 19:19:01,113 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 19:19:21,670 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 19:21:14,792 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 19:21:14,794 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 19:21:14,910 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 19:21:14,911 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 19:21:14,963 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-21 19:21:14,963 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-21 19:21:14,990 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-21 19:21:14,991 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-21 19:21:15,000 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-21 19:21:15,001 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-21 19:21:15,027 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-21 19:21:15,027 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-21 19:21:15,028 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-21 19:21:15,029 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-21 19:21:35,614 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-21 19:23:22,445 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 19:23:22,446 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-21 19:26:33,965 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-21 19:26:33,966 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-21 19:26:34,085 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-21 19:26:34,085 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
