[2025-04-13 19:48:36,733 INFO] [run_gptuner.py:<module>:107] Input arguments: Namespace(config='src/exp_configs/gpt4-4o-mini-overall.yml', folder='default', process='knowledge', db='postgres', database='tpcc_workload', test='tpcc', timeout=180, seed=100, result_path='./experiments_results/gpt4-4o-mini-overall_202504131948', model='gpt-4o-mini', restart_cmd='sudo docker restart tpcc_workload', recover_script='./scripts/recover_docker_postgres.sh', user='postgres', password='postgres')
[2025-04-13 19:50:48,601 WARNING] [run_gptuner.py:<module>:156] 'checkpoint_segments' is not in postgres
