[2025-04-28 15:37:55,208 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:37:55,299 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 15:39:27,158 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:39:27,214 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 15:39:47,424 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 15:40:12,244 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:41:48,893 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:41:48,951 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 15:42:09,161 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 15:42:33,832 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:42:33,888 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 15:42:33,920 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 15:42:54,094 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 15:43:18,948 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:43:19,005 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 15:43:19,040 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 15:43:48,111 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:44:08,379 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 15:44:33,162 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:44:33,255 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 15:46:10,286 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:46:10,381 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 15:46:30,573 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 15:46:55,138 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:46:55,198 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 15:47:15,394 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 15:47:40,082 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:49:13,949 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:49:14,051 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 15:50:46,198 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:50:46,293 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 15:52:26,365 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:52:46,625 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 15:53:11,266 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:53:11,324 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 15:53:31,451 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 15:53:56,126 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:53:56,226 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 15:54:16,408 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 15:54:41,107 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:54:41,204 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 15:56:13,248 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:56:13,306 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 15:57:45,599 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:57:45,687 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 15:58:07,698 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 15:58:32,347 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:58:32,410 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 15:58:52,628 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 15:59:17,331 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 15:59:37,608 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:00:02,234 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:00:22,477 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:00:47,034 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:00:47,090 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 16:01:07,302 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:01:31,917 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:01:52,166 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:02:16,878 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:02:16,934 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 16:02:37,053 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:03:01,823 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:03:22,108 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:03:46,804 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:03:46,862 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 16:04:07,102 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:04:31,890 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:04:31,989 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:04:54,351 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:05:18,937 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:05:19,027 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:05:39,271 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:06:03,977 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:06:26,232 ERROR] [postgres.py:update_dbms:117] Failed to execute "drop database if exists tpcc_template" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:06:26,232 ERROR] [postgres.py:update_dbms:117] Failed to execute "create database tpcc_template with template tpcc_workload" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:06:26,233 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:08:22,166 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:08:22,261 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:09:58,188 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:09:58,288 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:11:41,853 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:11:41,952 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:13:21,635 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:13:21,727 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:15:04,089 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:15:04,367 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:16:39,079 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:16:39,135 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 16:16:39,173 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:18:15,455 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:18:15,557 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:18:35,749 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:19:00,552 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:19:00,719 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 16:19:00,826 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:19:23,052 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:19:47,702 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:21:31,507 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:21:31,613 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:23:14,967 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:23:15,056 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:24:58,590 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:24:58,689 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:26:40,820 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:26:40,919 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:28:26,997 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:28:27,087 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:30:12,696 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:30:33,023 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:30:58,437 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:30:58,492 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 16:31:18,797 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:31:43,617 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:31:43,713 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:32:05,980 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:32:30,704 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:32:30,792 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:34:09,831 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:34:09,933 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:35:42,821 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:35:42,913 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:37:21,499 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:37:21,587 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:37:41,746 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:38:06,422 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:38:26,706 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:38:51,783 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:40:33,208 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:40:33,299 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:42:09,319 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:42:09,377 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 16:42:31,841 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:42:56,464 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:42:56,564 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:44:36,789 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:44:36,854 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 16:44:36,889 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:46:18,029 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:46:18,116 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:47:58,597 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:47:58,688 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:49:35,298 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:49:35,394 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:51:11,376 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:51:11,469 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:52:54,445 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:53:17,060 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:53:42,013 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:53:42,114 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:55:19,375 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:55:19,463 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:55:39,656 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 16:56:04,433 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:56:04,528 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 16:57:40,045 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:59:22,894 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 16:59:43,217 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 17:00:08,046 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:00:08,144 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:01:44,778 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:03:17,775 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:03:17,831 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 17:03:17,867 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:04:52,665 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:04:52,764 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:06:29,057 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:06:29,148 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:08:06,344 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:08:06,436 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:09:43,179 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:09:43,240 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 17:10:03,500 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 17:10:28,365 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:10:28,458 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:12:06,393 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:12:06,485 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:13:42,654 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:13:42,755 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:15:19,414 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:15:19,474 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 17:15:42,488 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 17:16:07,114 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:16:07,206 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:16:27,433 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 17:16:52,278 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:17:12,581 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 17:17:37,270 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:17:37,361 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:17:57,593 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 17:18:22,360 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:18:22,454 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:20:09,475 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:20:09,565 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:21:49,505 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:21:49,563 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 17:22:09,846 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 17:22:34,631 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:22:34,721 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:24:13,465 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:24:36,208 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 17:25:00,909 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:25:01,001 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:26:37,184 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:26:37,276 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:28:12,443 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:28:12,542 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:29:49,405 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:29:49,495 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:31:25,001 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:31:25,055 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 17:31:25,092 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:31:45,337 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 17:32:10,043 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:32:30,376 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 17:32:55,078 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:32:55,171 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:34:30,971 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:34:31,027 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 17:34:51,444 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 17:35:16,222 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:35:16,498 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:35:39,294 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 17:36:04,067 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:36:04,167 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:37:40,134 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:37:40,231 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:39:17,009 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:39:17,066 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 17:39:17,099 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:40:54,711 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:40:54,765 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 17:40:54,801 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:42:31,650 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:42:51,982 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 17:43:16,682 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:43:16,743 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 17:43:16,780 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:44:53,776 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:44:53,839 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 17:44:53,873 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:46:33,712 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:46:33,807 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:48:10,371 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:48:10,469 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:49:46,332 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:49:46,429 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:51:23,587 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:51:23,683 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:51:43,974 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-28 17:52:08,968 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:52:09,073 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:53:45,555 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:53:45,612 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 17:53:45,646 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:55:36,933 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:55:37,221 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-28 17:57:13,417 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-28 17:57:13,473 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-28 17:57:13,506 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

